# Handwitten Classification using ANN

In [2]:
import tensorflow as tf
from tensorflow import keras

In [3]:
#Lodaing the MNISt dataset
(x_train, y_train), (x_test, y_test) = keras.datasets.mnist.load_data()

In [4]:
#Normalize the pixel values between 0 and 1
x_train = x_train / 255.0
x_test = x_test / 255.0

In [5]:
#Define the ANN Model Architecture

model = keras.Sequential([
    keras.layers.Flatten(input_shape = (28, 28)),   #Convert the 28x28 image into a 1D Array
    keras.layers.Dense(128, activation = 'relu'),   #Hidden Layer with 128 Units
    keras.layers.Dense(10, activation = 'softmax')  #Output Layer with 10 units
])

In [6]:
#Complie the model
model.compile(optimizer = 'adam' , loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])

In [7]:
history = model.fit(x_train, y_train, epochs=5, validation_data = (x_test, y_test))

Epoch 1/5
1875/1875 [==============================] - 3s 1ms/step - loss: 0.2636 - accuracy: 0.9254 - val_loss: 0.1470 - val_accuracy: 0.9565
Epoch 2/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.1191 - accuracy: 0.9648 - val_loss: 0.1010 - val_accuracy: 0.9694
Epoch 3/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.0820 - accuracy: 0.9754 - val_loss: 0.0911 - val_accuracy: 0.9726
Epoch 4/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.0607 - accuracy: 0.9816 - val_loss: 0.0815 - val_accuracy: 0.9743
Epoch 5/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.0478 - accuracy: 0.9856 - val_loss: 0.0766 - val_accuracy: 0.9746


In [8]:
#Predict the Labels of the test set
import numpy as np
y_pred = model.predict(x_test)
y_pred = np.argmax(y_pred, axis = 1)

313/313 [==============================] - 0s 630us/step


In [9]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)

#print the Confusion Matrix
print('Confusion Matrix')
print(cm)

#Calculate the Accuracy
acc = accuracy_score(y_test, y_pred)

#Printing the Accuracy
print('Accuracy:', acc)

Confusion Matrix
[[ 970    0    0    3    1    1    1    1    3    0]
 [   0 1123    2    2    0    2    2    0    4    0]
 [   9    1  995    8    3    0    2    8    6    0]
 [   0    0    2 1000    0    2    0    3    2    1]
 [   2    0    4    1  952    0    3    3    1   16]
 [   2    0    0   15    1  865    3    0    4    2]
 [   7    3    2    1    2    8  932    0    3    0]
 [   2    4    7    6    2    1    0  993    2   11]
 [   7    1    3   15    4    6    2    1  930    5]
 [   3    3    0    7    3    4    0    2    1  986]]
Accuracy: 0.9746


In [ ]:
import matplotlib.pyplot as plt

#Plotting the Training and Validation Loss
plt.plot(history.history['loss'], label = 'Training Loss')
plt.plot(history.history['val_loss'], label = 'Validation Loss')
plt.title('Training and Validation Loss')
plt.xlabel('Epochs')
plt.ylabel('Loss')
plt.legend()
plt.show()

#Plotting the Training and Validation Accuracy 
plt.plot(history.history['accuracy'], label = 'Training Accuracy')
plt.plot(history.history['val_accuracy'], label = 'Validation Loss')
plt.title('Training and Validation Loss')
plt.xlabel('Epochs')
plt.ylabel('Loss')
plt.legend()
plt.show()